#!/bin/python3
import os
import subprocess

i = 1
filename = f"/tmp/a{i}.png"
while os.path.exists(filename):
    i += 1
    filename = f"/tmp/a{i}.png"


subprocess.run(["scrot", "--select", "-o", filename])
subprocess.Popen(["eog", filename],stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
